/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CriteriaRouteImport } from './routes/criteria'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LanesRouteImport } from './routes/lanes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PreordersRouteImport } from './routes/preorders'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as ShortlistRouteImport } from './routes/shortlist'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as ApiSignalsRouteImport } from './routes/api/signals'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronRefreshTrendsRouteImport } from './routes/api/cron/refresh-trends'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CriteriaRoute = CriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesRoute = LanesRouteImport.update({
  id: '/lanes',
  path: '/lanes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PreordersRoute = PreordersRouteImport.update({
  id: '/preorders',
  path: '/preorders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistRoute = ShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalsRoute = ApiSignalsRouteImport.update({
  id: '/api/signals',
  path: '/api/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRefreshTrendsRoute = ApiCronRefreshTrendsRouteImport.update({
  id: '/api/cron/refresh-trends',
  path: '/api/cron/refresh-trends',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/criteria': typeof CriteriaRoute
  '/history': typeof HistoryRoute
  '/lanes': typeof LanesRoute
  '/login': typeof LoginRoute
  '/preorders': typeof PreordersRoute
  '/procurement': typeof ProcurementRoute
  '/shortlist': typeof ShortlistRoute
  '/trends': typeof TrendsRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/refresh-trends': typeof ApiCronRefreshTrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/criteria': typeof CriteriaRoute
  '/history': typeof HistoryRoute
  '/lanes': typeof LanesRoute
  '/login': typeof LoginRoute
  '/preorders': typeof PreordersRoute
  '/procurement': typeof ProcurementRoute
  '/shortlist': typeof ShortlistRoute
  '/trends': typeof TrendsRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/refresh-trends': typeof ApiCronRefreshTrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/criteria': typeof CriteriaRoute
  '/history': typeof HistoryRoute
  '/lanes': typeof LanesRoute
  '/login': typeof LoginRoute
  '/preorders': typeof PreordersRoute
  '/procurement': typeof ProcurementRoute
  '/shortlist': typeof ShortlistRoute
  '/trends': typeof TrendsRoute
  '/api/signals': typeof ApiSignalsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/refresh-trends': typeof ApiCronRefreshTrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/criteria'
    | '/history'
    | '/lanes'
    | '/login'
    | '/preorders'
    | '/procurement'
    | '/shortlist'
    | '/trends'
    | '/api/signals'
    | '/api/auth/$'
    | '/api/cron/refresh-trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/criteria'
    | '/history'
    | '/lanes'
    | '/login'
    | '/preorders'
    | '/procurement'
    | '/shortlist'
    | '/trends'
    | '/api/signals'
    | '/api/auth/$'
    | '/api/cron/refresh-trends'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/criteria'
    | '/history'
    | '/lanes'
    | '/login'
    | '/preorders'
    | '/procurement'
    | '/shortlist'
    | '/trends'
    | '/api/signals'
    | '/api/auth/$'
    | '/api/cron/refresh-trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  CriteriaRoute: typeof CriteriaRoute
  HistoryRoute: typeof HistoryRoute
  LanesRoute: typeof LanesRoute
  LoginRoute: typeof LoginRoute
  PreordersRoute: typeof PreordersRoute
  ProcurementRoute: typeof ProcurementRoute
  ShortlistRoute: typeof ShortlistRoute
  TrendsRoute: typeof TrendsRoute
  ApiSignalsRoute: typeof ApiSignalsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronRefreshTrendsRoute: typeof ApiCronRefreshTrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criteria': {
      id: '/criteria'
      path: '/criteria'
      fullPath: '/criteria'
      preLoaderRoute: typeof CriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes': {
      id: '/lanes'
      path: '/lanes'
      fullPath: '/lanes'
      preLoaderRoute: typeof LanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preorders': {
      id: '/preorders'
      path: '/preorders'
      fullPath: '/preorders'
      preLoaderRoute: typeof PreordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlist': {
      id: '/shortlist'
      path: '/shortlist'
      fullPath: '/shortlist'
      preLoaderRoute: typeof ShortlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signals': {
      id: '/api/signals'
      path: '/api/signals'
      fullPath: '/api/signals'
      preLoaderRoute: typeof ApiSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/refresh-trends': {
      id: '/api/cron/refresh-trends'
      path: '/api/cron/refresh-trends'
      fullPath: '/api/cron/refresh-trends'
      preLoaderRoute: typeof ApiCronRefreshTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  CriteriaRoute: CriteriaRoute,
  HistoryRoute: HistoryRoute,
  LanesRoute: LanesRoute,
  LoginRoute: LoginRoute,
  PreordersRoute: PreordersRoute,
  ProcurementRoute: ProcurementRoute,
  ShortlistRoute: ShortlistRoute,
  TrendsRoute: TrendsRoute,
  ApiSignalsRoute: ApiSignalsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronRefreshTrendsRoute: ApiCronRefreshTrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
